name: Deploy to zip

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install API dependencies
        run: |
          cd foad-cicd/api
          npm install

      - name: Install Frontend dependencies and build
        run: |
          cd foad-cicd/front
          npm install
          npm run build

      - name: Debug before moving dist
        run: |
          echo "API directory:"
          ls -la foad-cicd/api
          echo "Front dist directory:"
          ls -la foad-cicd/front/dist

      - name: Move frontend dist to API public
        run: |
          rm -rf foad-cicd/api/public || true
          mkdir -p foad-cicd/api/public
          ls -la foad-cicd/api  
          mv foad-cicd/front/dist/* foad-cicd/api/public/

      - name: Verify files in API public
        run: ls -la foad-cicd/api/public

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - name: Create ZIP file
        run: zip -r my-project.zip .  

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-project-zip
          path: my-project.zip
