name: Deploy to zip

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Debug project structure
        run: |
          echo "Root directory:"
          ls -la
          echo "API directory:"
          ls -la foad-cicd/api || echo "API directory not found"
          echo "Front directory:"
          ls -la foad-cicd/front || echo "Front directory not found"

      - name: Install API dependencies
        run: |
          cd foad-cicd/api
          npm install

      - name: Install Frontend dependencies and build
        run: |
          cd foad-cicd/front
          npm install
          npm run build

      - name: Move frontend dist to API public
        run: |
          rm -rf foad-cicd/api/public
          mkdir -p foad-cicd/api/public
          mv foad-cicd/front/dist/* foad-cicd/api/public/

      - name: Build backend
        run: |
          cd foad-cicd/api
          npm run build  # Remplacez par votre commande de build si nécessaire

      - name: Install zip utility
        run: sudo apt-get install -y zip

      - name: Create ZIP file
        run: zip -r my-project.zip .  # Crée un fichier ZIP contenant tout le dépôt

      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-project-zip
          path: my-project.zip
